version: '3'

services:
  celerybeat:
    build: celerybeat/
    image: beats/celerybeat
    container_name: beats.celerybeat
    restart: always
    env_file:
      - .env
    network_mode: host

  filebeat:
    build: filebeat/
    image: beats/filebeat
    container_name: beats.filebeat
    restart: always
    privileged: true
    env_file:
      - .env
    volumes:
      - /var/log:/mnt/logs
      # - /etc/ssl/beats:/etc/ssl/beats
